variable "vpc_cidr" {}
variable "keypair-name" {}
variable "tag-vpc" {}
variable "path-to-pub-key" {}
variable "az1" {}
variable "az2" {}
variable "cidr-pub-01" {}
variable "cidr-pub-02" {}
variable "tag-pub-subnet1" {}
variable "tag-pub-subnet2" {}
variable "cidr-prt-1" {}
variable "tag-prt-subnet1" {}
variable "cidr-prt-2" {}
variable "tag-prt-subnet2" {}
variable "tag-igw" {}
variable "tag-nat" {}
variable "cidr-pub-RT" {}
variable "tag-pub-rt" {}
variable "tag-prt-rt" {}
